dummy_result = {
        "segments": [
            {
                "id": 1,
                "start": 0,
                "end": 8,
                "speaker": "SPEAKER_01",
                "text": "Voluptatem porro ipsum quisquam numquam quiquia magnam dolore.",
                "words": [
                    {
                        "start": 0,
                        "end": 1,
                        "word": "Voluptatem",
                        "speaker": "SPEAKER_01",
                        "confidence": 0.9,
                    },
                    {
                        "start": 1,
                        "end": 2,
                        "word": "porro",
                        "speaker": "SPEAKER_01",
                        "confidence": 0.9,
                    },
                    {
                        "start": 2,
                        "end": 3,
                        "word": "ipsum",
                        "speaker": "SPEAKER_01",
                        "confidence": 0.9,
                    },
                    {
                        "start": 3,
                        "end": 4,
                        "word": "quisquam",
                        "speaker": "SPEAKER_01",
                        "confidence": 0.9,
                    },
                    {
                        "start": 4,
                        "end": 5,
                        "word": "numquam",
                        "speaker": "SPEAKER_01",
                        "confidence": 0.9,
                    },
                    {
                        "start": 5,
                        "end": 6,
                        "word": "quiquia",
                        "speaker": "SPEAKER_01",
                        "confidence": 0.9,
                    },
                    {
                        "start": 6,
                        "end": 7,
                        "word": "magnam",
                        "speaker": "SPEAKER_01",
                        "confidence": 0.9,
                    },
                    {
                        "start": 7,
                        "end": 8,
                        "word": "dolore.",
                        "speaker": "SPEAKER_01",
                        "confidence": 0.9,
                    },
                ],
            },
            {
                "id": 2,
                "start": 8,
                "end": 15,
                "speaker": "SPEAKER_01",
                "text": "Est quaerat labore tempora aliquam ipsum etincidunt.",
                "words": [
                    {
                        "start": 8,
                        "end": 9,
                        "word": "Est",
                        "speaker": "SPEAKER_01",
                        "confidence": 0.9,
                    },
                    {
                        "start": 9,
                        "end": 10,
                        "word": "quaerat",
                        "speaker": "SPEAKER_01",
                        "confidence": 0.9,
                    },
                    {
                        "start": 10,
                        "end": 11,
                        "word": "labore",
                        "speaker": "SPEAKER_01",
                        "confidence": 0.9,
                    },
                    {
                        "start": 11,
                        "end": 12,
                        "word": "tempora",
                        "speaker": "SPEAKER_01",
                        "confidence": 0.9,
                    },
                    {
                        "start": 12,
                        "end": 13,
                        "word": "aliquam",
                        "speaker": "SPEAKER_01",
                        "confidence": 0.9,
                    },
                    {
                        "start": 13,
                        "end": 14,
                        "word": "ipsum",
                        "speaker": "SPEAKER_01",
                        "confidence": 0.9,
                    },
                    {
                        "start": 14,
                        "end": 15,
                        "word": "etincidunt.",
                        "speaker": "SPEAKER_01",
                        "confidence": 0.9,
                    },
                ],
            },
            {
                "id": 3,
                "start": 15,
                "end": 20,
                "speaker": "SPEAKER_01",
                "text": "Ipsum aliquam sed ipsum magnam.",
                "words": [
                    {
                        "start": 15,
                        "end": 16,
                        "word": "Ipsum",
                        "speaker": "SPEAKER_01",
                        "confidence": 0.9,
                    },
                    {
                        "start": 16,
                        "end": 17,
                        "word": "aliquam",
                        "speaker": "SPEAKER_01",
                        "confidence": 0.9,
                    },
                    {
                        "start": 17,
                        "end": 18,
                        "word": "sed",
                        "speaker": "SPEAKER_01",
                        "confidence": 0.9,
                    },
                    {
                        "start": 18,
                        "end": 19,
                        "word": "ipsum",
                        "speaker": "SPEAKER_01",
                        "confidence": 0.9,
                    },
                    {
                        "start": 19,
                        "end": 20,
                        "word": "magnam.",
                        "speaker": "SPEAKER_01",
                        "confidence": 0.9,
                    },
                ],
            },
            {
                "id": 4,
                "start": 20,
                "end": 25,
                "speaker": "SPEAKER_01",
                "text": "Voluptatem quaerat etincidunt magnam dolorem.",
                "words": [
                    {
                        "start": 20,
                        "end": 21,
                        "word": "Voluptatem",
                        "speaker": "SPEAKER_01",
                        "confidence": 0.9,
                    },
                    {
                        "start": 21,
                        "end": 22,
                        "word": "quaerat",
                        "speaker": "SPEAKER_01",
                        "confidence": 0.9,
                    },
                    {
                        "start": 22,
                        "end": 23,
                        "word": "etincidunt",
                        "speaker": "SPEAKER_01",
                        "confidence": 0.9,
                    },
                    {
                        "start": 23,
                        "end": 24,
                        "word": "magnam",
                        "speaker": "SPEAKER_01",
                        "confidence": 0.9,
                    },
                    {
                        "start": 24,
                        "end": 25,
                        "word": "dolorem.",
                        "speaker": "SPEAKER_01",
                        "confidence": 0.9,
                    },
                ],
            },
        ]
    }